# This file was generated by GoReleaser. DO NOT EDIT.
cask "terra" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "3a95eb8a67d04bb747409e3431be766864f635144cc7704a0da4358def6792e5"
      url "https://github.com/tryterra/terra-cli/releases/download/v#{version}/terra_#{version}_mac-os_x86_64.tar.gz",
        verified: "github.com/tryterra/terra-cli/"
    end
    on_arm do
      sha256 "783d0da9bb150ae7b0c54bf91513a6108256c80781a9df72a91a2da28a4fef6c"
      url "https://github.com/tryterra/terra-cli/releases/download/v#{version}/terra_#{version}_mac-os_arm64.tar.gz",
        verified: "github.com/tryterra/terra-cli/"
    end
  end

  name "terra"
  desc "Set up and debug your Terra integration from the terminal"
  homepage "https://docs.tryterra.co/developer-tools/terra-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terra"

  generate_completions_from_executable "terra",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
