# This file was generated by GoReleaser. DO NOT EDIT.
cask "terra" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "8d2104b73ee98c51f55d6170e220920e20a96347ab8990f10938c1074a3b477a"
      url "https://github.com/tryterra/terra-cli/releases/download/v#{version}/terra_#{version}_mac-os_x86_64.tar.gz",
        verified: "github.com/tryterra/terra-cli/"
    end
    on_arm do
      sha256 "13e3ebe4b38edfe83188e0084a1d0dfbfe91332cfc0118fecc79534ea773a869"
      url "https://github.com/tryterra/terra-cli/releases/download/v#{version}/terra_#{version}_mac-os_arm64.tar.gz",
        verified: "github.com/tryterra/terra-cli/"
    end
  end

  name "terra"
  desc "Set up and debug your Terra integration from the terminal"
  homepage "https://docs.tryterra.co/developer-tools/terra-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terra"

  generate_completions_from_executable "terra",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
