# This file was generated by GoReleaser. DO NOT EDIT.
cask "terra" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "362e81e718731cbc99ac7c1d8311348b7f437ee74a41095278fd744731637906"
      url "https://github.com/tryterra/terra-cli/releases/download/v#{version}/terra_#{version}_mac-os_x86_64.tar.gz",
        verified: "github.com/tryterra/terra-cli/"
    end
    on_arm do
      sha256 "c6474b1c2b60f71507d3d1e28f583cbcc3bc1ec9d935620c0a9d4ef16ecbe4b6"
      url "https://github.com/tryterra/terra-cli/releases/download/v#{version}/terra_#{version}_mac-os_arm64.tar.gz",
        verified: "github.com/tryterra/terra-cli/"
    end
  end

  name "terra"
  desc "Set up and debug your Terra integration from the terminal"
  homepage "https://docs.tryterra.co/developer-tools/terra-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "terra"

  generate_completions_from_executable "terra",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
